- hosts: personal_computers
  roles:
    - basic-system-config
    - basic-user-conifg
    - graphical-desktop-config
    - extra-packages
    - virtualization-tools

- hosts: test_vagrant_vms
  roles:
    - basic-system-config
    - basic-user-conifg

