- hosts: personal_computers
  roles:
    - basic-packages
    - basic-system-config
    - misc-user-config
    - ssh-config
    - dotfiles
    - graphical-desktop-config
    - extra-packages
    - virtualization-tools

