- hosts: localhost
  tasks:

    - name: check whether fasd is installed
      shell: which fasd
      register: fasd_check
      failed_when: fasd_check.rc > 1
      changed_when: fasd_check.rc == 1

    - when: fasd_check.rc == 1
      block:

        - name: clone fasd repository
          git:
            repo: "https://github.com/clvv/fasd"
            dest: "{{ ansible_env.HOME }}/bin/fasd.git"

        - name: install fasd
          shell: make install chdir={{ ansible_env.HOME }}/bin/fasd.git
          become: yes

    - name: clone smartless repository
      git:
        repo: "https://github.com/janek-warchol/smartless.git"
        dest: "~/bin/smartless.git"

    - name: create symlink to smartless
      file:
        src: ~/bin/smartless.git/smartless
        dest: ~/bin/smartless
        state: link
