- name: ensure .ssh directory exists
  file:
    path: ~/.ssh
    state: directory

- name: update ssh config
  copy:
    src: ssh-config-{{ ansible_env.USER }}
    dest: ~/.ssh/config
    backup: yes

- name: add my personal key to authorized keys
  lineinfile:
    dest: ~/.ssh/authorized_keys
    line: "{{ id_rsa_personal_2c6819cb_public_key }}"
    create: yes
