- name: create XDG and other directories
  file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: directory
  with_items:
    - "{{ xdg_documents_dir }}"
    - "{{ xdg_music_dir }}"
    - "{{ xdg_pictures_dir }}"
    - "{{ xdg_videos_dir }}"
    - janek
    - repos
    - zasoby

- name: update user-dirs.dirs
  template:
    src: user-dirs.j2
    dest: ~/.config/user-dirs.dirs

- name: remove default XDG directories
  # cannot use file module because I want to delete only empty directories
  shell: >
    rmdir
    Desktop
    Documents
    Downloads
    Music
    Pictures
    Public
    Templates
    Videos
    Pulpit
    Dokumenty
    Pobrane
    Muzyka
    Obrazy
    Publiczne
    Szablony
    Wideo
  args:
    chdir: "{{ ansible_env.HOME }}"
  register: task_result
  changed_when: task_result.stderr == ''
  failed_when: '"Directory not empty" in task_result.stderr'

  # I prefer to keep installed fonts in another location
- name: update fonts directory location
  shell: >
    if [ -d ~/.fonts ]; then
        mv -n ~/.fonts ~/zasoby/czcionki
    else
        mkdir ~/zasoby/czcionki
    fi
    creates=~/zasoby/czcionki

- name: create link to ~/.fonts
  file:
    src: ~/zasoby/czcionki
    dest: ~/.fonts
    state: link
    force: no

- name: make links between config files in HOME and data dir
  shell: >
    if [ -e {{item.dest}} -a ! -e {{item.src}} ]; then
        ln {{item.dest}} {{item.src}}
        echo "link created"
    elif [ -e {{item.src}} -a ! -e {{item.dest}} ]; then
        ln {{item.src}} {{item.dest}}
        echo "link created"
    elif [ -e {{item.src}} -a -e {{item.dest}} ]; then
        diff {{item.src}} {{item.dest}} 1>&2
    fi
  register: task_result
  changed_when: '"link created" in task_result.stdout'
  with_items: 
    - src: ~/janek/gtk-bookmarks
      dest: ~/.config/gtk-3.0/bookmarks
    - src: ~/janek/monitors.xml
      dest: ~/.config/monitors.xml
    - src: ~/janek/viminfo
      dest: ~/.viminfo
