- name: check for dotfiles
  stat: path=~/.config/dotfiles-git-dir
  register: dotfiles_config_file

# we must not try cloning the repo if it already exists, because the
# installation script ran in the next task transforms it and ansible
# would be confused.
- name: clone dotfiles
  git:
    repo: "git://github.com/janek-warchol/my-dotfiles"
    dest: ~/.dotfiles.git
    version: janek
    force: no
  when: dotfiles_config_file.stat.exists == false

- name: install dotfiles
  shell: >
    ~/.dotfiles.git/.install-dotfiles.sh
    creates=~/.config/dotfiles-git-dir
  when: dotfiles_config_file.stat.exists == false

# provide initial config of the repo (most importantly remotes).
- name: install dotfiles git repo configuration
  copy:
    src: dotfiles-repo-config
    dest: ~/.dotfiles.git/config
  when: dotfiles_config_file.stat.exists == false

- name: create .vim/autoload
  file:
    dest: ~/.vim/autoload
    state: directory

- name: download plug.vim
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.vim/autoload/plug.vim
