- name: check for dotfiles
  stat: path=~/.config/dotfiles-git-dir
  register: dotfiles_config_file

# My dotfiles installation script is not idempotent, so we must skip
# installation tasks if the dotfiles are already present.
# TODO
# Note that I initially clone using https and later change the protocol
# to SSH.  This is because my SSH keys may not be present when cloning,
# and because I need different urls for work account SSH configuration.
- name: clone dotfiles
  git:
    repo: "https://github.com/janek-warchol/my-dotfiles"
    dest: "{{ dotfiles_dir }}"
    version: janek
    force: no
  when: dotfiles_config_file.stat.exists == false

- name: install dotfiles
  shell: >
    {{ dotfiles_dir }}/.install-dotfiles.sh
    creates=~/.config/dotfiles-git-dir
  when: dotfiles_config_file.stat.exists == false
  register: dotfiles_installation

- name: report installation results
  debug: var=dotfiles_installation.stdout_lines
  when: dotfiles_installation.changed

- name: update remote url to use SSH protocol
  lineinfile:
    dest: "{{ dotfiles_dir }}/config"
    line: "	url = {{ dotfiles_remote_url }}"
    regexp: url =

  # I don't want to accidentally commit something with my work email.
- name: override git authorship setting in dotfiles repo
  blockinfile:
    dest: "{{ dotfiles_dir }}/config"
    block: |
      [user]
      	name = Jan Warchoł
      	email = jan.warchol@gmail.com
  # don't use "inventory_hostname in groups.xxx" construct
  # because it fails when group xxx is not defined.  This is better.
  when: "'work_computers' in group_names"

- name: vim - create .vim/autoload
  file:
    dest: ~/.vim/autoload
    state: directory

# The nice thing about vim-plug (https://github.com/junegunn/vim-plug)
# is that it can be installed just by downloading one file.
- name: vim - install plugin manager
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.vim/autoload/plug.vim

# TODO: detect task status (changed/unchanged)
- name: vim - install plugins
  shell: vim +PlugInstall +qall
