- name: check for dotfiles
  stat: path=~/.config/dotfiles-git-dir
  register: dotfiles_config_file

# My dotfiles installation script is not idempotent, so we must skip
# installation tasks if the dotfiles are already present.
# TODO
# Note that I initially clone using https and later change the protocol
# to SSH.  This is because my SSH keys may not be present when cloning,
# and because I need different urls for work account SSH configuration.
- name: clone dotfiles
  git:
    repo: "https://github.com/jan-warchol/my-dotfiles"
    dest: "{{ dotfiles_dir }}"
    version: devel
    force: no
  when: dotfiles_config_file.stat.exists == false

- name: install dotfiles
  shell: >
    {{ dotfiles_dir }}/.install-dotfiles.sh
    creates=~/.config/dotfiles-git-dir
  when: dotfiles_config_file.stat.exists == false
  register: dotfiles_installation

- name: report installation results
  debug: var=dotfiles_installation.stdout_lines
  when: dotfiles_installation.changed

- name: update remote url to use SSH protocol
  lineinfile:
    dest: "{{ dotfiles_dir }}/config"
    line: "	url = {{ dotfiles_remote_url }}"
    regexp: url =
