- name: check for dotfiles
  stat: path=~/.config/dotfiles-git-dir
  register: dotfiles_config_file

# we must not try cloning the repo if it already exists, because the
# installation script ran in the next task transforms it and ansible
# would be confused.
# TODO
# Note that I initially clone using https and later change the protocol
# to SSH.  This is because my SSH keys may not be present when cloning,
# and because I need different urls for work account SSH configuration.
- name: clone dotfiles
  git:
    repo: "https://github.com/janek-warchol/my-dotfiles"
    dest: ~/.dotfiles.git
    version: janek
    force: no
  when: dotfiles_config_file.stat.exists == false

- name: install dotfiles
  shell: >
    ~/.dotfiles.git/.install-dotfiles.sh
    creates=~/.config/dotfiles-git-dir
  when: dotfiles_config_file.stat.exists == false

- name: update remote url to use SSH protocol
  lineinfile:
    dest: ~/.dotfiles.git/config
    line: "	url = {{ dotfiles_remote_url }}"
    regexp: url =

  # I don't want to accidentally commit something with my work email.
- name: override git authorship setting in dotfiles repo
  blockinfile:
    dest: ~/.dotfiles.git/config
    block: |
      [user]
      	name = Jan Warchoł
      	email = jan.warchol@gmail.com
  when: inventory_hostname in groups.work_computers

- name: create .vim/autoload
  file:
    dest: ~/.vim/autoload
    state: directory

- name: download plug.vim
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.vim/autoload/plug.vim
