- name: check for dotfiles
  stat: path=~/.config/dotfiles-git-dir
  register: dotfiles_config_file

- name: clone dotfiles
  git:
    repo: "git://github.com/janek-warchol/my-dotfiles"
    dest: ~/.dotfiles.git
    version: janek
  when: dotfiles_config_file.stat.exists == false

- name: install dotfiles
  shell: >
    ~/.dotfiles.git/.install-dotfiles.sh
    creates=~/.config/dotfiles-git-dir
  when: dotfiles_config_file.stat.exists == false

- name: install dotfiles git repo configuration
  copy:
    src: dotfiles-git-config
    dest: ~/.dotfiles.git/config
