# See http://xmodulo.com/how-to-install-or-upgrade-virtualbox-on-ubuntu-or-debian.html

- name: add VirtualBox repo apt key
  apt_key: url=http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc
  sudo: yes

- name: add VirtualBox PPA
  apt_repository:
    repo='deb http://download.virtualbox.org/virtualbox/debian trusty contrib non-free'
  sudo: yes

- name: install VirtualBox
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - virtualbox-4.3
    - virtualbox-guest-dkms
  sudo: yes
