- name: create XDG directories
  file:
    path: "{{ ansible_env.HOME }}/media/{{ item }}"
    state: directory
  with_items:
    - wymiana
    - muzyka
    - filmy
    - obrazy

- name: user-dirs.dirs file
  copy:
    src: user-dirs
    dest: ~/.config/user-dirs.dirs

- name: file manager bookmarks
  copy:
    src: bookmarks
    dest: ~/.config/gtk-3.0/bookmarks
    backup: yes

- name: remove unneeded directories
  shell: rmdir "{{ ansible_env.HOME }}/{{ item }}"
  with_items:
    - Desktop
    - Documents
    - Downloads
    - Music
    - Pictures
    - Public
    - Templates
    - Videos
    - Pulpit
    - Dokumenty
    - Pobrane
    - Muzyka
    - Obrazy
    - Publiczne
    - Szablony
    - Wideo
  register: task_result
  changed_when: task_result.stderr == ''
  failed_when: '"Directory not empty" in task_result.stderr'

- name: Update xkb files
  copy:
    src: "{{ ansible_env.HOME }}/.config/xkb/{{ item.src }}"
    dest: /usr/share/X11/xkb/{{ item.dest }}
  with_items:
    - { src: symbols/janek, dest: symbols/janek }
    - { src: symbols/modifier_keys, dest: symbols/modifier_keys }
    - { src: keycodes/customThinkPad, dest: keycodes/customThinkPad }
  sudo: yes

- name: Update xorg.conf
  copy:
    src: xorg.conf
    dest: /etc/X11/xorg.conf
  sudo: yes

- name: set Terminator as default system terminal
  shell: >
    gsettings get org.cinnamon.desktop.default-applications.terminal exec;
    gsettings set org.cinnamon.desktop.default-applications.terminal exec 'terminator'
  register: previous_default
  changed_when: '"terminator" not in previous_default.stdout'

- name: check whether xcape is installed
  stat: path=~/bin/xcape
  register: xcape_executable

- include: install-xcape.yml
  when: xcape_executable.stat.exists == false
