# FIXME
# Ansible's apt_repository module doesn't work correcty with Linux Mint,
# see https://github.com/ansible/ansible/issues/4587
# Also, the filenames that are checked for existence are hardcoded :(

- name: Add official git PPA
  command: >
    add-apt-repository --yes ppa:git-core/ppa
    creates=/etc/apt/sources.list.d/git-core-ppa-trusty.list
  sudo: yes

- name: Add FreeFileSync PPA
  command: >
    add-apt-repository --yes ppa:freefilesync/ffs
    creates=/etc/apt/sources.list.d/freefilesync-ffs-trusty.list
  sudo: yes

#- name: FreeFileSync wasn't available in Utopic Unicorn repos
#  shell: sed -i 's/utopic/trusty/' /etc/apt/sources.list.d/freefilesync*
#  sudo: yes

- name: Add Google Chrome APT key
  apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub
  sudo: yes

- name: add Google Chrome APT repository
  apt_repository: repo='deb http://dl.google.com/linux/chrome/deb/ stable main'
  sudo: yes

- name: Install all additional software
  apt:
    name: "{{ item }}"
    state: latest
    install_recommends: no
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - baobab
    - build-essential
    - dconf-cli
    - dconf-editor   # desktop environment configuration
    - flip
    - freefilesync
    - git
    - gitk
    - google-chrome-stable
    - gparted
    - indicator-multiload
    - ipython
    - kate
    - keepass2
    - xdotool   # library for auto-type in keepass
    - libdvdread4   # DVD decryption
    - openjdk-7-jre
    - python-dev
    - python-virtualenv
    - python-numpy
    - python-scipy
    - python-matplotlib
    - python-tk
    - sshfs
    - terminator
    - vim
    - vlc
    - xbacklight   # changing screen brightness
    #- gimp
    #- guake
    #- imagemagick
    #- kompare
  sudo: yes

# TODO
# I think this is not needed anymore...
#- name: Finish DVD decryption installation
#  shell: /usr/share/doc/libdvdread4/install-css.sh
#  sudo: yes
