- name: Ensure xkb directories exist
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - ~/.config/xkb/symbols
    - ~/.config/xkb/keycodes

- name: Update xkb files
  template:
    src: xkb/{{ item }}
    dest: ~/.config/xkb/{{ item }}
  with_items:
    - janek.xkb
    - janek-shifted.xkb
    - symbols/janek
    - symbols/modifier_keys
    - keycodes/customThinkPad
    - keycodes/evdev-shifted
