- name: check whether xcape is installed
  stat: path=~/bin/xcape
  register: xcape_executable

- include: install-xcape.yml
  when: xcape_executable.stat.exists == false

- name: Ensure xkb directories exist
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - ~/.config/xkb/symbols
    - ~/.config/xkb/keycodes

- name: Update xkb files
  template:
    src: xkb/{{ item }}
    dest: ~/.config/xkb/{{ item }}
  with_items:
    - janek.xkb
    - symbols/janek
    - symbols/modifier_keys
    - keycodes/customThinkPad
