- name: clone smartless repository
  git:
    repo: "https://github.com/stefanheule/smartless.git"
    dest: "~/bin/smartless.git"

- name: create symlink to smartless
  file:
    src: ~/bin/smartless.git/smartless
    dest: ~/bin/smartless
    state: link
