- include: install-ansible.yml

- include: install-equalizer.yml

- include: install-chrome.yml

- include: install-packages.yml

- name: check whether dropbox is installed
  shell: which dropbox
  register: dropbox_check
  failed_when: dropbox_check.rc > 1
  changed_when: dropbox_check.rc == 1

- include: install-dropbox.yml
  when: dropbox_check.rc == 1

