- name: update ansible-system-setup remote
  lineinfile:
    dest: ~/.config/ansible-system-setup/.git/config
    regexp: url = .*ansible-system-setup
    line: "	url = git@bitbucket.org:janek-warchol/ansible-system-setup.git"
  when: ansible_env.USER == "janek"

- name: update ansible-system-setup remote
  lineinfile:
    dest: ~/.config/ansible-system-setup/.git/config
    regexp: url = .*ansible-system-setup
    line: "	url = git@bitbucket-personal:janek-warchol/ansible-system-setup.git"
  when: ansible_env.USER == "codilime"

- name: set commit authorship metadata in ansible-system-setup
  blockinfile:
    dest: ~/.config/ansible-system-setup/.git/config
    block: |
      [user]
      	name = Jan Warchoł
      	email = jan.warchol@gmail.com

- name: create vagrant.d directory
  file:
    dest: "{{ ansible_env.HOME }}/.vagrant.d"
    state: directory

- name: install vagrant configuration
  template:
    src: global-vagrantfile
    dest: "{{ ansible_env.HOME }}/.vagrant.d/Vagrantfile"

- name: generate ssh key for vagrant boxes
  command: >
    ssh-keygen
    -f {{ ansible_env.HOME }}/.ssh/custom_vagrant_key
    -N ""
    -C custom_vagrant_key
  args:
    creates: "{{ ansible_env.HOME }}/.ssh/custom_vagrant_key"